name: Release

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: Cache yarn cache
      uses: actions/cache@v1
      with:
        path: ~/.cache/yarn
        key: ${{ runner.os }}-yarn-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - name: Install and build
      run: |
        yarn --frozen-lockfile
        yarn build
      env:
        CI: true
    - name: Publish with vsce
      run: |
        npm i -g vsce
        # Try to publish and ignore any errors (that version was already published)
        vsce publish -p $VSCE_TOKEN || true
      env:
        VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}
